### ISSUE TITLE
[bug] Tableau errors when connecting to projects with parameterised databricks Server Hostname and HTTP Path

### ISSUE THREAD

**Issue by block-benjamin** [dbt-labs/semantic-layer-tableau-connector#1]
## Is this a new bug in [semantic-layer-tableau-connector](https://github.com/dbt-labs/semantic-layer-tableau-connector)?
- [x] I believe this is a new bug in semantic-layer-tableau-connector
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

## Current Behavior
when connecting, from tableau desktop, to a semantic layer with a databricks based project using environmental variables for the connection Tableau attempts to connect to the variable name not the variable value.

## Expected Behavior
The tableau connector uses the environmental variable defined for the selected environment in the semantics layer config.

## Steps To Reproduce
1. configure the connection to databricks with the following
  - Adaptor: Databricks (dbt-databricks)
  - Server Hostname: {env_var(DBT_HOSTNAME)]}.azuredatabricks.net
  - HTTP Path: /sql/1.0/warehouses/{{env_var('DBT_HTTP_PATH')}}
 2. assign environment variables in the deploy pane.
 3. configure the semantic layer for your environment
 4. generate a semantic layer service token
 5. connect from table desktop using the dbt connector

## Relevant log output
<img width="998" alt="image" src="https://github.com/dbt-labs/semantic-layer-tableau-connector/assets/106250537/1969c468-d936-4553-a910-03e94d71bc8a">

## Additional Info
replacing the projects environmental variables with a defined server hostname and http path the dbt connector works. however this prevents different workspaces from being used for development and deployment.

**Comment by aiguofer** [comment]
Hi, I'm assuming you are setting up your Semantic Layer credentials in dbt Cloud using those environment variables?

We don't support that currently. We only support a single set of Semantic Layer credentials that are tied to a single deployment environment at this time. We're planning on supporting multiple environments for a single project in the future but we're not quite there yet.

That being said, you can use the cloud cli to test the Semantic Layer against development. You can also use the MetricFlow cli. However, you can't use either of those with tableau.

**Comment by block-benjamin** [comment]
@aiguofer thank you. Apologies, I didn't catch that limitation when reviewing the dbt documentation. Good to know support for multiple environments from a single project is planned in the future.

Appreciate the cli suggestions as a work around.
